intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{spirv-headers}: {hxx ixx txx h}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{spirv-headers}:
{
  cc.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cc.export.libs = $intf_libs
}

# Install recreating subdirectories.
#
{hxx ixx txx h}{*}:
{
  install         = include/
  install.subdirs = true
}
